name: akshaya_flutter_app
description: Akshaya Resurrection App
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  provider: ^6.0.5
  audioplayers: ^4.1.0

flutter:
  uses-material-design: true
